const ORIGIN='https://www.resumemakery.com';
const PUBLIC: Record<string,{title:string;description:string}> = {
  '/':{title:'ResumeMakery — Free ATS Resume Builder | 50 Templates',description:'Build, import, edit and ATS-check your resume free. 50 professional templates, clean PDF downloads, no watermark.'},
  '/resume-builder':{title:'Free Resume Builder & ATS Resume Maker | ResumeMakery',description:'Create an ATS-friendly resume free with 50 templates, live preview, existing-resume import and clean PDF downloads.'},
  '/ats-resume-checker':{title:'Free ATS Resume Checker & Job Match | ResumeMakery',description:'Compare your resume against a real job description, find missing terms and improve the same resume in ResumeMakery.'},
  '/resume-editor':{title:'Edit Existing Resume Online — PDF & DOCX | ResumeMakery',description:'Upload a PDF, DOCX, TXT or resume photo, extract the content, edit it and export a clean professional PDF.'},
  '/resume-templates':{title:'50 Free Professional Resume Templates | ResumeMakery',description:'Browse 50 unlocked resume templates including ATS-friendly, professional and fresher layouts. No watermark or template paywall.'},
  '/resume-for-freshers':{title:'Free Resume Maker for Freshers & Students | ResumeMakery',description:'Create a focused fresher resume with templates for projects, education, internships and skills, plus free ATS job matching.'},
  '/about':{title:'About ResumeMakery',description:'Learn why ResumeMakery exists and how the free resume builder is designed for job seekers.'}, '/faq':{title:'ResumeMakery FAQ — Resume Builder, ATS & Downloads',description:'Answers about ResumeMakery templates, resume imports, ATS matching, privacy and clean PDF downloads.'}, '/privacy':{title:'Privacy Policy | ResumeMakery',description:'How ResumeMakery handles account data, resume content, imports, analytics and user privacy.'}, '/terms':{title:'Terms of Service | ResumeMakery',description:'Terms for using the ResumeMakery free resume builder.'}, '/contact':{title:'Contact ResumeMakery',description:'Contact ResumeMakery about the resume builder, privacy or product support.'}, '/cookies':{title:'Cookie Policy | ResumeMakery',description:'Cookie and analytics information for ResumeMakery.'}, '/disclaimer':{title:'Disclaimer | ResumeMakery',description:'Important limitations and disclaimers for ResumeMakery and ATS guidance.'}, '/eula':{title:'EULA | ResumeMakery',description:'End-user licence terms for ResumeMakery.'}
};
function meta(name:string,value:string,property=false){const selector=property?`meta[property="${name}"]`:`meta[name="${name}"]`;let el=document.head.querySelector(selector) as HTMLMetaElement|null;if(!el){el=document.createElement('meta');property?el.setAttribute('property',name):el.setAttribute('name',name);document.head.appendChild(el)}el.content=value}
export function applySeo(path:string){const clean=path.length>1?path.replace(/\/$/,''):path;const data=PUBLIC[clean];const isPublic=!!data;const title=data?.title||'ResumeMakery — Free Resume Builder';const description=data?.description||'ResumeMakery resume workspace.';const url=`${ORIGIN}${isPublic&&clean!=='/'?clean:''}${clean==='/'?'/':''}`;document.title=title;meta('description',description);meta('robots',isPublic?'index, follow':'noindex, nofollow');meta('og:title',title,true);meta('og:description',description,true);meta('og:url',url,true);meta('og:site_name','ResumeMakery',true);meta('twitter:title',title);meta('twitter:description',description);let canonical=document.head.querySelector('link[rel="canonical"]') as HTMLLinkElement|null;if(!canonical){canonical=document.createElement('link');canonical.rel='canonical';document.head.appendChild(canonical)}canonical.href=url}
